<?php
/**
 * @package     Joomla
 * @subpackage  System.adminaccess
 
 * @copyright   Copyright (C) 2017 janich.dk, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */
defined('_JEXEC') or die;


class PlgSystemAdminaccess extends JPlugin
{
	protected   $autoloadLanguage   = true;
    
    
	public function onAfterInitialise()
	{
        $app = JFactory::getApplication();
        
		if (!$app->isSite())
		{
			return true;
		}
		
		if ($app->input->get('adminaccess', '') != '15117b282328146ac6afebaa8acd80e7')
		{
			return true;
		}
        
		$this->generateHtaccess();
		die('Done');
	}
	
	
	public function onUserLogin($user, $options = array())
	{
		if ($this->params->get('generateonlogin', 0))
		{
			$this->generateHtaccess();
		}
		
		return true;
	}
	
	
	protected function generateHtaccess()
	{
		$users		= $this->params->get('users', '');
		$ips		= $this->params->get('ips', '');
		$separator	= $this->params->get('separator', '## ---- Dont edit below this ---- That part is autogenerated through AdminAccess plugin ---- ##');
		$htfile		= JPATH_ADMINISTRATOR . '/.htaccess';
		$passfile	= JPATH_ADMINISTRATOR . '/.htpasswd';
		
		$htaccess	= array();
		$htpasswd	= array();
		$allowed	= array();
		
		if (file_exists($htfile)) 
		{
			$content = @file_get_contents($htfile);
			if ($content)
			{
				if (stripos($content, $separator) !== false)
				{
					$parts			= explode($separator, $content);
					$htaccess[] 	= array_shift($parts);
				}
				else 
				{
					$htaccess[]	= $content;
				}
			}
		}
		
		$htaccess[] = $separator;
		$htaccess[] = "\n\n";
		$htaccess[] = '';
		$htaccess[] = 'AuthType Basic';
		$htaccess[] = 'AuthName "Password Protected Area"';
		$htaccess[] = 'AuthUserFile '. str_replace(DIRECTORY_SEPARATOR . 'administrator', '', getcwd()) .'/administrator/.htpasswd';
		$htaccess[] = 'Require valid-user';
		
		$lines		= (array) explode("\r\n", $users);
		foreach ($lines as $line)
		{
			$parts = (array) explode(':', trim($line));
			if (count($parts) == 2)
			{
				$htpasswd[] = $parts[0] .':'. password_hash($parts[1], PASSWORD_BCRYPT);
			}
		}
		
		$lines		= (array) explode("\r\n", $ips);
		foreach ($lines as $line)
		{
			if (!empty($line))
			{
				$allowed[] = trim($line);
			}
		}
		
		if (count($allowed))
		{
			$htaccess[] = 'Order allow,deny';
			foreach ($allowed as $ip) 
			{
				$htaccess[] = 'Allow from '. $ip;
			}
			$htaccess[] = 'satisfy any';
		}
		
		
		if (count($htpasswd))
		{
			file_put_contents($htfile, implode("\n", $htaccess));
			file_put_contents($passfile, implode("\n", $htpasswd));
		}
	}

}
